name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: gradle/wrapper-validation-action@v1

      -   name: Run release build
          run: ./gradlew assembleRelease

      -   name: Run debug build
          run: ./gradlew assembleDebug

      -   name: Upload artifact to GitHub
          uses: actions/upload-artifact@v2
          with:
            name: MGConferenceApp Debug Build
            path: app/build/outputs/apk/debug/app-debug.apk

      -   name: Run lint
          run: ./gradlew lint
